/* Shared page components and public, conceptual case studies. */
const cases = [
 {slug:'rolling-forecast', old:'forecast', number:'01', label:'SEE', name:'ROLLING FORECAST', title:'다음 3개월의 손익은 어디에서 움직일까?', summary:'판매·생산·재고·원가를 연결해 미래 손익과 주요 변동 요인을 살펴봅니다.', question:'판매계획이 늘면, 이익도 같은 속도로 늘어날까?', context:'판매량이 같아도 생산과 재고, 투입 원가에 따라 손익은 달라집니다. 다음 3개월을 전망하려면 각 계획의 시점과 연결 관계부터 맞춰야 합니다.', steps:[['가정을 연결합니다.','판매 물량과 단가, 생산 계획, 재고 수불을 같은 월 기준으로 정리합니다.'],['손익이 만들어지는 흐름을 봅니다.','생산량과 투입 단가의 변화가 재고와 매출원가에 언제 반영되는지 추적합니다.'],['매월 차이를 되짚습니다.','실적이 확정되면 이전 전망과 비교하고, 변동 이유를 다음 달 가정에 반영합니다.']], outputs:['3개월 손익 전망','주요 가정과 변동 요인','전월 전망 대비 차이'], takeaway:'하나의 예상 숫자와 함께, 그 숫자가 달라지는 조건을 설명합니다.', related:'/writing/see01-rolling-forecast/', relatedTitle:'제조업 3개월 Rolling Forecast는 어떻게 만들어지는가'},
 {slug:'profitability', old:'profitability', number:'02', label:'EXPLAIN', name:'PROFITABILITY ANALYSIS', title:'같은 이익에도, 다른 이유가 있습니다.', summary:'계획과 실적의 차이를 물량·가격·원가로 나눠 변화의 원인을 설명합니다.', question:'목표 이익을 달성했으면, 사업도 계획대로 움직였을까?', context:'최종 이익이 같아도 매출과 비용의 움직임은 다를 수 있습니다. 물량 증가가 가격 하락과 원가 상승을 상쇄했다면, 다음 달에 관리해야 할 요인도 달라집니다.', steps:[['비교 기준을 맞춥니다.','계획·전월 전망·전년 실적 중 어떤 기준과 비교하는지 먼저 정하고, 품목과 기간의 범위를 통일합니다.'],['영향을 나눕니다.','물량·가격·원가 요인을 일관된 계산 순서로 분해합니다. 제품 구성과 교차 효과를 확인해 중복 계산을 피합니다.'],['지속성과 대응을 봅니다.','일시적인 효과와 반복되는 변화를 구분하고, 다음 전망에 반영할 가정과 관리 우선순위를 정리합니다.']], outputs:['손익 변동 브리지','핵심 요인별 영향','지속성·관리 포인트'], takeaway:'총액이 같다는 사실만으로, 변화가 없었다고 판단하지 않습니다.'},
 {slug:'investment', old:'investment', number:'03', label:'DECIDE', name:'INVESTMENT DECISION', title:'투자 판단의 기준을 선명하게 만듭니다.', summary:'투자 규모와 현금흐름, 가정의 변화를 함께 놓고 의사결정을 지원합니다.', question:'이 투자는 어떤 조건에서 타당할까?', context:'수익성 지표는 검토의 출발점입니다. 물량·가격·가동 시점 같은 가정이 달라질 때 현금흐름이 어떻게 바뀌는지 함께 봐야 판단의 범위가 드러납니다.', steps:[['투자 범위를 정의합니다.','초기 투자와 추가 지출, 운전자본, 가동 일정 등 검토에 포함할 범위와 기준을 정리합니다.'],['가정을 현금흐름으로 바꿉니다.','운영 시나리오를 기간별 현금흐름으로 연결하고, 동일한 기준에서 NPV·IRR·회수기간을 함께 살펴봅니다.'],['조건별 판단을 정리합니다.','주요 가정의 민감도와 하방 시나리오를 검토해 진행·보완·재검토에 필요한 조건을 명확히 합니다.']], outputs:['투자 현금흐름','수익성·민감도 검토','조건별 의사결정 기준'], takeaway:'단일 수익률과 함께, 그 수익률을 성립시키는 가정과 리스크를 제시합니다.'},
 {slug:'budget', old:'budget', number:'04', label:'CONTROL', name:'BUDGET & PERFORMANCE', title:'예산의 차이를 다음 행동으로 바꿉니다.', summary:'계획과 실적의 차이를 발견하고, 원인·담당·후속 확인으로 연결합니다.', question:'예산을 초과했다면, 무엇부터 확인해야 할까?', context:'총액의 초과 여부만으로는 대응 방향이 분명하지 않습니다. 집행 시점의 차이인지, 활동량이 늘었는지, 단가나 지출 범위가 바뀌었는지부터 구분해야 합니다.', steps:[['차이를 발견합니다.','계획과 실적을 같은 기간·조직·비용 항목으로 비교하고, 주의가 필요한 항목을 확인합니다.'],['원인을 분류합니다.','활동량·단가·일정·일회성 요인으로 나누고, 통제 가능한 부분과 설명이 필요한 부분을 구분합니다.'],['행동과 확인을 연결합니다.','원인별 담당과 다음 조치를 정하고, 후속 점검 시점에 실적과 전망이 달라졌는지 확인합니다.']], outputs:['예산 대비 차이','원인별 관리 항목','담당·조치·점검 일정'], takeaway:'차이의 크기를 보고하는 데서 나아가, 누가 무엇을 확인할지 정리합니다.'}
];
const forecastStages = [
 ['판매','판매 계획에서 출발합니다.','품목별 판매량과 단가를 연결해 매출을 추정합니다. 수요와 납기 가정이 바뀌면 후속 계획도 함께 확인합니다.'],
 ['생산','판매와 생산의 차이를 확인합니다.','판매 계획에 재고 목표와 생산 여건을 반영합니다. 생산량과 가동 수준의 변화는 단위당 원가에도 영향을 줍니다.'],
 ['재고','입고·투입·판매 사이의 시차를 봅니다.','원재료·재공품·제품의 수불을 연결해 어떤 원가가 재고로 남고, 어떤 원가가 손익으로 이동하는지 살펴봅니다.'],
 ['원가','판매된 제품의 원가를 연결합니다.','투입 재료비와 가공비, 재고 흐름을 반영해 매출원가를 추정합니다. 구매가격의 변화가 곧바로 매출원가에 반영되는 것은 아닙니다.'],
 ['손익','변동 요인을 담은 전망을 만듭니다.','매출·매출원가·판관비를 연결해 손익을 추정하고, 전망을 움직이는 핵심 가정과 리스크를 함께 정리합니다.']
];
function header(active='') {
 return `<a class="skip-link" href="#main">본문으로 건너뛰기</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="AFTER THE NUMBERS 홈">AFTER THE NUMBERS<span class="brand-period">.</span></a><button class="menu-button" data-menu aria-controls="site-navigation" aria-expanded="false" hidden>메뉴 <span aria-hidden="true">☰</span></button><nav class="site-navigation" id="site-navigation" aria-label="주요 메뉴">${[['cases','/#case','분석 사례'],['writing','/writing/','글'],['career','/#career','경력·역량'],['contact','/#about','연락처']].map(([key,url,label])=>`<a href="${url}"${active===key?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header>`;
}
function footer(){return `<footer class="site-footer"><div class="wrap"><span>© 2026 AFTER THE NUMBERS</span><span>숫자 뒤의 변화와 의사결정.</span><a href="/#intro">맨 위로 ↑</a></div></footer>`;}
function miniVisual(type) {
 const inside = type==='forecast'?'<path d="M15 77L80 47L145 61"/><path class="mini-blue" stroke-dasharray="6 6" d="M145 61L210 30L280 13"/><circle cx="145" cy="61" r="4"/>':type==='profitability'?'<path class="mini-guide" d="M8 87H290"/><rect x="16" y="32" width="40" height="55"/><rect class="mini-blue" x="91" y="12" width="40" height="20"/><rect x="166" y="12" width="40" height="8"/><rect x="241" y="32" width="40" height="55"/><path class="mini-guide" d="M56 32H91M131 12H166M206 20H241"/>':type==='investment'?'<path class="mini-guide" d="M25 22L150 50L275 22M25 78L150 50L275 78"/><circle cx="25" cy="22" r="6"/><circle cx="25" cy="78" r="6"/><circle class="mini-blue" cx="150" cy="50" r="20"/><circle cx="275" cy="22" r="6"/><circle cx="275" cy="78" r="6"/>':'<path class="mini-guide" stroke-dasharray="5 5" d="M5 30H290"/><path d="M15 81L145 54L275 17"/><circle class="mini-blue" cx="275" cy="17" r="7"/>';
 return `<svg viewBox="0 0 300 100" class="mini-visual" aria-hidden="true">${inside}</svg>`;
}
function caseCards(){return cases.map(c=>`<a class="case-card" id="case-${c.old}" href="/cases/${c.slug}/"><div class="case-card-top"><span class="case-number">${c.number}</span><span class="eyebrow">${c.label}</span><span class="card-arrow" aria-hidden="true">↗</span></div><h3>${c.title}</h3><p>${c.summary}</p><div class="case-card-bottom"><span class="case-name">${c.name}</span>${miniVisual(c.old)}</div><span class="case-open">사례 자세히 보기 <span aria-hidden="true">→</span></span></a>`).join('');}
function caseGraphic(c){
 if(c.old==='forecast') return `<div data-stage-explorer><div class="stage-tabs" aria-label="손익 추정 단계" hidden>${forecastStages.map((s,i)=>`<button type="button" data-stage-button id="stage-tab-${i}" aria-controls="stage-panel-${i}"><span>0${i+1}</span>${s[0]}</button>`).join('')}</div><div class="flow-diagram" aria-hidden="true">${forecastStages.map((s,i)=>`<span data-flow-node>${s[0]}${i<4?'<i>→</i>':''}</span>`).join('')}</div>${forecastStages.map((s,i)=>`<section class="stage-panel" data-stage-panel id="stage-panel-${i}"><span class="eyebrow">0${i+1} / ${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p></section>`).join('')}</div>`;
 if(c.old==='profitability') return `<figure class="case-figure"><figcaption>이익 100 → 100, 그 사이의 변화</figcaption><div class="waterfall-wrap"><svg class="waterfall" viewBox="0 0 640 260" role="img" aria-label="계획 이익 100에 물량 효과 8을 더하고, 가격 효과 3과 원가 효과 5를 차감하면 실적 이익 100입니다."><path class="chart-grid" d="M20 211H620"/><g fill="#14283e"><rect x="35" y="77" width="70" height="134"/><rect x="535" y="77" width="70" height="134"/></g><rect fill="#2864b5" x="160" y="29" width="70" height="48"/><g fill="#ab765c"><rect x="285" y="29" width="70" height="18"/><rect x="410" y="47" width="70" height="30"/></g><path class="waterfall-connect" d="M105 77H160M230 29H285M355 47H410M480 77H535"/><g class="waterfall-value"><text x="70" y="62">100</text><text x="195" y="18">+8</text><text x="320" y="18">−3</text><text x="445" y="35">−5</text><text x="570" y="62">100</text></g><g class="waterfall-label"><text x="70" y="243">계획</text><text x="195" y="243">물량</text><text x="320" y="243">가격</text><text x="445" y="243">원가</text><text x="570" y="243">실적</text></g></svg></div><p class="diagram-note">개념을 설명하기 위한 예시입니다. 증감 구간은 변화가 잘 보이도록 확대 표시했습니다.</p></figure>`;
 if(c.old==='investment') return `<div class="decision-path"><div><span>01 / SCOPE</span><h3>투자 범위</h3><p>투자금액 · 일정 · 운전자본</p></div><div><span>02 / CASH FLOW</span><h3>운영 시나리오</h3><p>물량 · 가격 · 비용 · 현금흐름</p></div><div><span>03 / SENSITIVITY</span><h3>수익성과 리스크</h3><p>NPV · IRR · 회수기간 · 민감도</p></div><div class="decision-final"><span>04 / DECISION</span><h3>조건별 판단</h3><p>진행 · 보완 · 재검토</p></div></div>`;
 return `<figure class="case-figure"><figcaption>차이의 발견에서 후속 점검까지</figcaption><div class="budget-example"><div class="budget-amount"><span>예산 지수</span><strong>100</strong></div><div class="budget-amount"><span>실적 지수</span><strong>104</strong></div><div class="budget-amount budget-gap"><span>확인할 차이</span><strong>+4</strong></div></div><ol class="action-path"><li><b>원인</b><span>활동량 · 단가 · 집행 시점</span></li><li><b>조치</b><span>담당 · 대응 내용 · 기한</span></li><li><b>점검</b><span>후속 실적 · 전망 반영</span></li></ol><p class="diagram-note">설명용 예시 · 초과 집행의 원인에 따라 필요한 조치는 달라집니다.</p></figure>`;
}
function casePage(c,head){
 const next = cases[(cases.indexOf(c)+1)%cases.length];
 return `<!doctype html><html lang="ko"><head>${head}<link rel="stylesheet" href="/styles.css"><script src="/script.js" defer></script></head><body>${header('cases')}<main id="main" class="wrap case-detail"><a class="back-link" href="/#case">← 분석 사례 목록</a><header class="case-detail-hero"><p class="eyebrow">CASE ${c.number} / ${c.label} · ${c.name}</p><h1>${c.title}</h1><p class="detail-lead">${c.summary}</p></header><div class="case-detail-body"><aside class="case-brief"><span class="eyebrow">THE QUESTION</span><h2>${c.question}</h2><p>${c.context}</p><div class="output-list"><span class="eyebrow">OUTPUT</span><ul>${c.outputs.map(x=>`<li>${x}</li>`).join('')}</ul></div></aside><div class="case-main"><section class="case-demo"><p class="eyebrow">ANALYSIS IN VIEW</p>${caseGraphic(c)}</section><section class="approach"><p class="eyebrow">HOW I APPROACH IT</p><h2>분석은 이렇게 이어집니다.</h2><ol>${c.steps.map((s,i)=>`<li><span class="step-number">0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div></li>`).join('')}</ol></section><blockquote class="case-takeaway">${c.takeaway}</blockquote>${c.related?`<a class="related-story" href="${c.related}"><span class="eyebrow">RELATED WRITING</span><h3>${c.relatedTitle}</h3><span>글 읽기 ↗</span></a>`:''}</div></div><nav class="case-pagination" aria-label="다른 분석 사례"><a class="text-link" href="/#case">전체 사례</a><a href="/cases/${next.slug}/"><small>다음 사례 / ${next.label}</small><strong>${next.title} <span aria-hidden="true">↗</span></strong></a></nav></main>${footer()}</body></html>`;
}
module.exports = {cases, header, footer, caseCards, casePage};
